# -- 코드를 입력하세요
# SELECT HOUR(DATETIME) HOUR, COUNT(ANIMAL_ID) COUNT
# FROM ANIMAL_OUTS
# GROUP BY HOUR(DATETIME)
# HAVING HOUR >= 9 AND HOUR <= 19
# ORDER BY HOUR

select HOUR(DATETIME) as HOUR, count(animal_id) as COUNT
from ANIMAL_OUTS 
where HOUR(DATETIME) >= 9 and HOUR(DATETIME) <= 19
group by HOUR(DATETIME)
order by HOUR